name: laravel_app

services:
  php:
    build: ./php
    environment:
      MYSQL_HOST: mysql
      MYSQL_DB: test
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno
    volumes:
      - ./src:/var/www/html
      - ./php/conf.d:/usr/local/etc/php/conf.d

  nginx:
    image: nginx:latest
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./src:/var/www/html:ro
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro

  mysql:
    image: mysql:8
    environment:
      MYSQL_ROOT_PASSWORD: administrador
      MYSQL_USER: alumno
      MYSQL_PASSWORD: alumno
      MYSQL_DATABASE: test
    ports:
      - "3307:3306"        # ← evita choque con MySQL nativo
    volumes:
      - mysql_data:/var/lib/mysql   # ← volumen nombrado (NO bind al host)
      - ./mysql:/docker-entrypoint-initdb.d:ro  # opcional para scripts .sql

volumes:
  mysql_data:

networks:
  default:
    driver: bridge

